#include "ft2build.h"
#include FT_FREETYPE_H
#include FT_GLYPH_H
#include FT_OUTLINE_H
#include FT_BITMAP_H
#include FT_TRUETYPE_TABLES_H
#include FT_SFNT_NAMES_H
#include FT_BBOX_H
#include FT_STROKER_H
#include FT_SYNTHESIS_H
#include FT_BITMAP_H
#include FT_TRIGONOMETRY_H
#include FT_MODULE_ERRORS_H
