// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Hexa.NET.X3DAudio
{
    public unsafe struct X3DAudioHandle
    {
        public fixed byte Data[20];
    }
}