namespace HexaGen
{
    public sealed class CodeWriter : IDisposable
    {
        private readonly string[] _indentStrings;
        private readonly string @namespace;
        private readonly IEnumerable<string> usings;

        private StreamWriter _writer;

        private int lines;
        private int blocks = 0;
        private int indentLevel;


        private string _indentString = "";
        private bool _shouldIndent = true;

        public int IndentLevel { get => indentLevel; }

        public string FileName { get; }


        public CodeWriter(string fileName, string @namespace, IEnumerable<string> usings)
        {
            FileName = fileName;
            this.@namespace = @namespace;
            this.usings = usings;
            _indentStrings = new string[10];
            for (int i = 0; i < _indentStrings.Length; i++)
            {
                _indentStrings[i] = new string('\t', i);
            }

            _writer = File.CreateText(fileName);
            _writer.WriteLine("// ------------------------------------------------------------------------------");
            _writer.WriteLine("// <auto-generated>");
            _writer.WriteLine("//     This code was generated by a tool.");
            _writer.WriteLine("//");
            _writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            _writer.WriteLine("//     the code is regenerated.");
            _writer.WriteLine("// </auto-generated>");
            _writer.WriteLine("// ------------------------------------------------------------------------------");
            _writer.WriteLine();

            foreach (string ns in usings)
            {
                _writer.WriteLine($"using {ns};");
            }

            if (usings.Any())
            {
                _writer.WriteLine();
            }

            BeginBlock($"namespace {@namespace}");
        }


        public long Length => _writer.BaseStream.Length;

        public int Lines => lines;

        public void Dispose()
        {
            EndBlock();
            _writer.Dispose();
        }

        public void Write(char chr)
        {
            WriteIndented(chr);
        }

        public void Write(string @string)
        {
            WriteIndented(@string);
        }

        public void WriteLine()
        {
            _writer.WriteLine();
            _shouldIndent = true;
        }

        public void WriteLine(string @string)
        {
            WriteIndented(@string);
            _writer.WriteLine();
            _shouldIndent = true;
            lines++;
        }

        public void WriteLines(string? @string, bool newLineAtEnd = false)
        {
            if (@string == null)
                return;

            if (@string.Contains('\n'))
            {
                var lines = @string.Split('\n', StringSplitOptions.RemoveEmptyEntries);
                for (int i = 0; i < lines.Length; i++)
                {
                    WriteIndented(lines[i]);
                    _shouldIndent = true;
                    this.lines++;
                }
            }
            _shouldIndent = true;
        }

        public void WriteLines(IEnumerable<string> lines)
        {
            foreach (var line in lines)
            {
                WriteLine(line);
            }
        }

        public void BeginBlock(string content)
        {
            WriteLine(content);
            WriteLine("{");
            Indent(1);
            blocks++;
        }

        public void EndBlock()
        {
            if (blocks <= 0)
                return;
            blocks--;
            Dedent(1);
            WriteLine("}");
        }

        public IDisposable PushBlock(string marker = "{") => new CodeBlock(this, marker);

        public void Indent(int count = 1)
        {
            indentLevel += count;

            if (IndentLevel < _indentStrings.Length)
            {
                _indentString = _indentStrings[IndentLevel];
            }
            else
            {
                _indentString = new string('\t', IndentLevel);
            }
        }

        public void Dedent(int count = 1)
        {
            if (count > indentLevel)
                throw new ArgumentException("count out of range.", nameof(count));

            indentLevel -= count;
            if (indentLevel < _indentStrings.Length)
            {
                _indentString = _indentStrings[indentLevel];
            }
            else
            {
                _indentString = new string('\t', indentLevel);
            }
        }

        private void WriteIndented(char chr)
        {
            if (_shouldIndent)
            {
                _writer.Write(_indentString);
                _shouldIndent = false;
            }

            _writer.Write(chr);
        }

        private void WriteIndented(string @string)
        {
            if (_shouldIndent)
            {
                _writer.Write(_indentString);
                _shouldIndent = false;
            }

            _writer.Write(@string);
        }

        public readonly struct CodeBlock : IDisposable
        {
            private readonly CodeWriter _writer;

            public CodeBlock(CodeWriter writer, string content)
            {
                _writer = writer;
                _writer.BeginBlock(content);
            }

            public void Dispose()
            {
                _writer.EndBlock();
            }
        }

    }
}
