name: Build SDL2 Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libsdl-org/SDL'
        ref: 'release-2.30.6'
        path: 'SDL'

    - name: Checkout specific commit
      run: |
        cd SDL
        git checkout ba2f78a

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android SDK Command-Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android-sdk-tools.zip
        unzip android-sdk-tools.zip -d android-sdk
        sudo mkdir /usr/src/android-sdk/
        sudo mkdir /usr/src/android-sdk/cmdline-tools/
        sudo mkdir /usr/src/android-sdk/cmdline-tools/latest/
        sudo mv ./android-sdk/cmdline-tools/* /usr/src/android-sdk/cmdline-tools/latest/
        sudo chmod +x /usr/src/android-sdk/cmdline-tools/latest/bin/*
        echo "ANDROID_HOME=/usr/src/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/src/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/src/android-sdk/cmdline-tools/latest/bin:/usr/src/android-sdk/platform-tools" >> $GITHUB_ENV
        
    - name: Accept Android SDK Licenses
      run: |
        yes | sudo /usr/src/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Install Specific Android NDK Version 26.3.11579264
      run: |
        yes | sudo /usr/src/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"      
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV

    - name: Build for arm64-v8a
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=OFF \
                -DSDL_SHARED=ON \
                -S SDL \
                -B SDL/build/arm64-v8a
          cmake --build SDL/build/arm64-v8a  --config Release

    - name: Build for x86_64
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=OFF \
                -DSDL_SHARED=ON \
                -S SDL \
                -B SDL/build/x86_64
          cmake --build SDL/build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          SDL/build/arm64-v8a/*.so
          SDL/build/x86_64/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
