name: Build SDL2 Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libsdl-org/SDL'
        ref: 'release-2.30.6'
        path: 'SDL'

    - name: Checkout specific commit
      run: |
        cd SDL
        git checkout ba2f78a

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build openjdk-8-jdk ant android-sdk-platform-tools-common

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

    - name: Download and Install Android NDK r10e
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
        unzip android-ndk-r10e-linux-x86_64.zip
        sudo mv android-ndk-r10e /usr/src/android-ndk-r10e
        echo "ANDROID_NDK_HOME=/usr/src/android-ndk-r10e" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/src/android-ndk-r10e" >> $GITHUB_ENV

    - name: Build for arm64-v8a
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=OFF \
                -DSDL_SHARED=ON \
                -S SDL \
                -B SDL/build/arm64-v8a
          cmake --build SDL/build/arm64-v8a  --config Release

    - name: Build for x86_64
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DSDL_STATIC=OFF \
                -DSDL_SHARED=ON \
                -S SDL \
                -B SDL/build/x86_64
          cmake --build SDL/build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          SDL/build/arm64-v8a/*.so
          SDL/build/x86_64/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
