#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codecs_common.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h264std.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h265std.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h264std_decode.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h265std_decode.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h264std_encode.h"
#include "C:\VulkanSDK\1.3.250.0\Include\vk_video\vulkan_video_codec_h265std_encode.h"

#include "include/vulkan_core.h"
#include "include/vulkan.h"
